# Generated by Django 5.0.1 on 2024-01-13 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="members",
        ),
    ]
